# -----------------------------------------------------------------------------
# Kanagawa Paper Canvas
# Upstream: https://github.com/thesimonho/kanagawa-paper.nvim/master/extras/alacritty/kanagawa-paper-canvas.toml
# URL: https://github.com/alacritty/alacritty
# -----------------------------------------------------------------------------

[colors.primary]
background = '#e1e1de'
foreground = '#84908e'

[colors.cursor]
cursor = '#929fb9'
text = '#e1e1de'

[colors.selection]
background = '#d4cdd4'
foreground = '#9d9992'

[colors.normal]
black = '#b7b7a9'
red = '#c58c89'
green = '#8ba59e'
yellow = '#b9a679'
blue = '#91acb8'
magenta = '#a690a8'
cyan = '#929fb9'
white = '#b7b7a9'

[colors.bright]
black = '#bebeb0'
red = '#c99895'
green = '#93aea7'
yellow = '#c2ae7f'
blue = '#a0bdca'
magenta = '#af9bb0'
cyan = '#9da8c0'
white = '#bebeb0'

[[colors.indexed_colors]]
index = 16
color = '#c39e87'

[[colors.indexed_colors]]
index = 17
color = '#c58c89'
