name: Build Extras
on:
  workflow_dispatch:
  push:
    paths:
      - "**/*.lua"
      - "lua/kanagawa-paper/extras/**"
  pull_request:
    types: [closed]
    paths:
      - "**/*.lua"
      - "lua/kanagawa-paper/extras/**"
jobs:
  extras:
    name: Build Extras
    runs-on: ubuntu-latest
    if: github.event_name == 'push' || github.event_name == 'workflow_dispatch' || github.event.pull_request.merged == true
    permissions:
      contents: write
    steps:
      - uses: actions/checkout@v4
      - uses: rhysd/action-setup-vim@v1
        with:
          neovim: true
      - name: Set permissions
        run: chmod +x scripts/build.sh
      - name: Run build script
        run: |
          scripts/build.sh || { echo "❌ Build script failed!"; exit 1; }
          git add -f extras/
      - name: Pull latest changes before commit
        run: |
          git pull --rebase origin ${{ github.ref_name }}
      - uses: stefanzweifel/git-auto-commit-action@v5
        with:
          commit_message: "build(extras): auto build themes for extras"
