name: Generate Palette
on:
  workflow_dispatch:
  push:
    paths:
      - "lua/kanagawa-paper/colors.lua"
jobs:
  generate:
    name: Generate Palette
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: leafo/gh-actions-lua@v11
        with:
          luaVersion: "5.1"
      - name: Run generate script
        run: lua scripts/generate_palette.lua
      - name: Stash changes if needed
        run: |
          git stash push || echo "No changes to stash"
      - name: Pull latest changes with rebase
        run: |
          git pull --rebase origin HEAD
      - name: Restore stash if needed
        run: |
          git stash pop || echo "No changes to restore"
      - uses: stefanzweifel/git-auto-commit-action@v5
        with:
          commit_message: "docs(palette): auto generate palette preview"
